language: perl
perl:
- '5.30'
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
install:
- cpanm File::Find::Rule~0.34
- cpanm Geo::Address::Formatter
script:
- bin/run_tests.t
notifications:
  slack:
    secure: M7U87fLJ7oXOPjFDBASOwhNZXqRoYsTYtPxVbAHlQfS1at38IfK7/6rWdf7yNUPCV0JqfRCsR7frWQNncR9BbjtYSoDFywY/IcdVMoOl3haZJqXbA/LfGgI9ZIBAx5nBUlZkBaaq/RhXoKlNbZ89p6zq3qyvsUIgmUSkNTGejRU=
